spring:
  profiles:
    active: dev

---
server:
  port: 80
spring:
  profiles: dev
  application:
    name: springcloud-product-feign-config
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true

---
server:
  port: 90
spring:
  profiles: pro
  application:
    name: springcloud-product-feign-config
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true