spring:
  profiles:
    active: dev

---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: springcloud-eureka-config

eureka:
  instance:
    hostname: eureka6001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false

---
server:
  port: 6101
spring:
  profiles: pro
  application:
    name: springcloud-eureka-config

eureka:
  instance:
    hostname: eureka6001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka6002.com:6102/eureka/
  server:
    enable-self-preservation: true
